# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spec < Formula
  desc "Developer control plane CLI"
  homepage "https://github.com/aaronl1011/spec"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronl1011/spec/releases/download/v0.15.0/spec_0.15.0_darwin_amd64.tar.gz"
      sha256 "8c89a9b54e83870a69f7f42582ec690e7e9c71da07b28dededb16dcac936e0de"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronl1011/spec/releases/download/v0.15.0/spec_0.15.0_darwin_arm64.tar.gz"
      sha256 "df87326b006c19ee0aacd89b132de9a3f48876363c4999500e23e1761b8c30b9"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec/releases/download/v0.15.0/spec_0.15.0_linux_amd64.tar.gz"
      sha256 "672c1039ad0ee3459c77d973865ceb349c730f152dac4ced0f6eb69aac2c8da8"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec/releases/download/v0.15.0/spec_0.15.0_linux_arm64.tar.gz"
      sha256 "36c7c80d2526cecd17cc76b64ad60039852a9808e89ae72c09a674860897042f"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  test do
    system "#{bin}/spec", "version"
  end
end
