# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spec < Formula
  desc "Developer control plane CLI"
  homepage "https://github.com/aaronl1011/spec"
  version "0.41.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronl1011/spec/releases/download/v0.41.0/spec_0.41.0_darwin_amd64.tar.gz"
      sha256 "c5edf3573616eb98019b6f65bca97969ef20db210cb0041f59f3f115e2ab01ed"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronl1011/spec/releases/download/v0.41.0/spec_0.41.0_darwin_arm64.tar.gz"
      sha256 "6f789ab620d1abd691e3105722567e9d0b7f6f910eefe482567254cf3b6a2bb0"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec/releases/download/v0.41.0/spec_0.41.0_linux_amd64.tar.gz"
      sha256 "0408e4421d2c05810261e4247f636f81b2f87fac1c0674e910aef78d9b4b5a4a"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec/releases/download/v0.41.0/spec_0.41.0_linux_arm64.tar.gz"
      sha256 "dfefbdfd1bebf2e0ec0d24fb11c357adb31b3eff36e2ff16682b3f02596485ef"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  test do
    system "#{bin}/spec", "version"
  end
end
