# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spec < Formula
  desc "Developer control plane CLI"
  homepage "https://github.com/aaronl1011/spec"
  version "0.39.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronl1011/spec/releases/download/v0.39.2/spec_0.39.2_darwin_amd64.tar.gz"
      sha256 "06765ca4750d73779e5e15c383e999dadca4877e86af837c4caf4009f08dffdc"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronl1011/spec/releases/download/v0.39.2/spec_0.39.2_darwin_arm64.tar.gz"
      sha256 "4f05a8d05fc1faa2422cc820cfe1b93ac4947bf58495a4cfc784eed273367e52"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec/releases/download/v0.39.2/spec_0.39.2_linux_amd64.tar.gz"
      sha256 "987670d2046a0336fbc97626d23b85062c5afb8a1a91f2ee09b9fe55bfaa952b"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec/releases/download/v0.39.2/spec_0.39.2_linux_arm64.tar.gz"
      sha256 "440ddee4997021608a5dbc8d70c1ebd0ca781088fd3375d4fdd4284407cf6ff5"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  test do
    system "#{bin}/spec", "version"
  end
end
