# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpecCli < Formula
  desc "Developer control plane CLI"
  homepage "https://github.com/aaronl1011/spec-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.3.0/spec-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "fc537bfdfd80aedb4290bebb26aab68590277e23ac62975e67c6ef7a02564804"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.3.0/spec-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "3447542ce3c774bce562673bbc4af055a74df480e109da591d2f7d0c6a34904e"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.3.0/spec-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "e4742abf5a68bbd8d960b3ee012c94486b45d3fd8fdf5e72c53ed930cf502d09"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.3.0/spec-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "c67917d799e98db549e8d41aceb8010f4257c9a6b7d5a8b665a57fd2a83a8e83"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  test do
    system "#{bin}/spec", "version"
  end
end
