# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpecCli < Formula
  desc "Developer control plane CLI"
  homepage "https://github.com/aaronl1011/spec-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.1.4/spec-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "104cc25f54eba72e839a61c919177e6feb64a9bca52e473db8270920454416c4"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.1.4/spec-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "199720c7d33c5379afca0834f4b2d97c3a1654503a709d2895367bd2dcf1e702"

      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.1.4/spec-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "5803fc3ad59f5ed0eca724c3da77c80b096a14317f030d0e0830c58ae0e1e1f8"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronl1011/spec-cli/releases/download/v0.1.4/spec-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "ceb794d29018c819cc7e4eba53f4b54854658f3c0d553386c716b2e2f2698ef9"
      define_method(:install) do
        bin.install "spec"
        man1.install Dir["docs/man/*.1"] if Dir.exist?("docs/man")
      end
    end
  end

  test do
    system "#{bin}/spec", "version"
  end
end
